# Generated by Django 4.1.4 on 2023-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeaApp', '0002_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='titulo',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
