# Generated by Django 4.1.4 on 2023-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeaApp', '0003_seccion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='color_fondo',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
