# Generated by Django 4.1.4 on 2023-04-20 14:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeaApp', '0004_seccion_color_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='color_fondo',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='contenido',
            field=models.TextField(),
        ),
    ]
