# Generated by Django 4.1.4 on 2023-04-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
